In [ ]:
import mysql.connector
mydb = mysql.connector.connect(host='localhost', user='root', password='Akopk@27',
                               database="bank_management", auth_plugin='mysql_native_password')


def main():
    print("""
           1. OPEN NEW ACCOUNT   
           2. DEPOSIT AMOUNT
           3. WITHDRAW AMOUNT
           4. BALANCE ENQUIRY
           5. DISPLAY CUSTOMER DETAILS
           6. CLOSE AN ACCOUNT
           7. TRANSFER MONEY""")
    choice = input("Enter the Task You want to perform")
    if(choice == '1'):
        OpenAcc()
    elif(choice == '2'):
        DespoAmo()
    elif(choice == '3'):
        WithdrawAmount()
    elif(choice == '4'):
        BalEnq()
    elif(choice == '5'):
        DisDetails()
    elif(choice == '6'):
        CloseAcc()
    elif(choice == '7'):
        TransferMoney()
    else:
        print("Invalid Choice")

    main()






def OpenAcc():
    n = input("Enter The Name: ")
    ac = input("Enter the Accont No: ")
    db = input("Enter the date of Birth: ")
    add = input("Enter The address: ")
    cn = input("Enter the contact number: ")
    ob = int(input("Enter the opening Balance: "))
    data1 = (n, ac, db, add, cn, ob)
    data2 = (n, ac, ob)
    sql1 = ('insert into account values (%s,%s,%s,%s,%s,%s)')
    sql2 = ('insert into amount values(%s,%s,%s)')
    x = mydb.cursor()
    x.execute(sql1, data1)
    x.execute(sql2, data2)
    mydb.commit()
    print("Data Entered Succesfully")
    main()


def DespoAmo():
    amount = int(input("Enter the amount you want to deposit"))
    ac = input("Enter the account number")
    a = 'select balance from amount where AccNo=%s'
    data = (ac,)
    x = mydb.cursor()
    x.execute(a, data)
    result = x.fetchone()
    print(result)
    t = int(result[0])+amount
    sql = ('update amount set balance=%s where AccNo=%s')
    d = (t, ac)
    print(d)
    x.execute(sql, d)
    mydb.commit()
    main()


def BalEnq():
    ac = input("Enter the account no: ")
    a = 'select * from amount where AccNo=%s'
    data = (ac,)
    x = mydb.cursor()
    x.execute(a, data)
    result = x.fetchone()
    print("Balanne for account: ", ac, "is", result[-1])
    main()


def DisDetails():
    ac = input("Enter the account no: ")
    a = 'select * from account where AccNo=%s'
    data = (ac,)
    x = mydb.cursor()
    x.execute(a, data)
    result = x.fetchone()
    for i in result:
        print(i)
    main()


def CloseAcc():
    ac = input("Enter the account no: ")
    sql1 = 'delete from account where Accno=%s'
    sql2 = 'delete from amount where AccNo=%s'
    data = (ac,)
    x = mydb.cursor()
    x.execute(sql1, data)
    x.execute(sql2, data)
    mydb.commit()
    main()


def WithdrawAmount():
    amount = int(input("Enter the amount you want to Withdraw"))
    ac = input("Enter the account number")
    a = 'select balance from amount where AccNo=%s'
    data = (ac,)
    x = mydb.cursor()
    x.execute(a, data)
    result = x.fetchone()
    print(result)
    t = int(result[0])-amount
    sql = ('update amount set balance=%s where AccNo=%s')
    d = (t, ac)
    print(d)
    x.execute(sql, d)
    mydb.commit()
    main()


def TransferMoney():
    sac = input("Enter your account Number: ")
    rac = input("Enter recivers account Number: ")
    amt = int(input("Enter amout you want to send: "))
    send(sac, amt)
    rec(rac, amt)
    print("Money Transfered Succesfully")
    main()


def send(ac, amount):
    a = 'select balance from amount where AccNo=%s'
    data = (ac,)
    x = mydb.cursor()
    x.execute(a, data)
    result = x.fetchone()
    print(result)
    t = int(result[0])-amount
    sql = ('update amount set balance=%s where AccNo=%s')
    d = (t, ac)
    print(d)
    x.execute(sql, d)
    mydb.commit()


def rec(ac, amount):
    a = 'select balance from amount where AccNo=%s'
    data = (ac,)
    x = mydb.cursor()
    x.execute(a, data)
    result = x.fetchone()
    print(result)
    t = int(result[0])+amount
    sql = ('update amount set balance=%s where AccNo=%s')
    d = (t, ac)
    print(d)
    x.execute(sql, d)
    mydb.commit()
main()

           1. OPEN NEW ACCOUNT
           2. DEPOSIT AMOUNT
           3. WITHDRAW AMOUNT
           4. BALANCE ENQUIRY
           5. DISPLAY CUSTOMER DETAILS
           6. CLOSE AN ACCOUNT
           7. TRANSFER MONEY
Enter the Task You want to perform1
Enter The Name: praveen
Enter the Accont No: 11111
Enter the date of Birth: 22/01/1990
Enter The address: chennai
Enter the contact number: 767678
Enter the opening Balance: 3000
Data Entered Succesfully

           1. OPEN NEW ACCOUNT
           2. DEPOSIT AMOUNT
           3. WITHDRAW AMOUNT
           4. BALANCE ENQUIRY
           5. DISPLAY CUSTOMER DETAILS
           6. CLOSE AN ACCOUNT
           7. TRANSFER MONEY
Enter the Task You want to perform5
Enter the account no: 12345
DAKSH k
12345
27/01/2001
dwarka,delhi
920544
3000

           1. OPEN NEW ACCOUNT
           2. DEPOSIT AMOUNT
           3. WITHDRAW AMOUNT
           4. BALANCE ENQUIRY
           5. DISPLAY CUSTOMER DETAILS
           6. CLOSE AN ACCOUNT
           7. TRANSFER MONEY
Enter the Task You want to perform7
Enter your account Number: 12345
Enter recivers account Number: 11111
Enter amout you want to send: 1000
(7000,)
(6000, '12345')
(3000,)
(4000, '11111')
Money Transfered Succesfully

           1. OPEN NEW ACCOUNT
           2. DEPOSIT AMOUNT
           3. WITHDRAW AMOUNT
           4. BALANCE ENQUIRY
           5. DISPLAY CUSTOMER DETAILS
           6. CLOSE AN ACCOUNT
           7. TRANSFER MONEY
Enter the Task You want to perform5
Enter the account no: 11111
praveen
11111
22/01/1990
chennai
767678
3000

           1. OPEN NEW ACCOUNT
           2. DEPOSIT AMOUNT
           3. WITHDRAW AMOUNT
           4. BALANCE ENQUIRY
           5. DISPLAY CUSTOMER DETAILS
           6. CLOSE AN ACCOUNT
           7. TRANSFER MONEY
Enter the Task You want to perform7
Enter your account Number: 12345
Enter recivers account Number: 11111
Enter amout you want to send: 10000
(6000,)
(-4000, '12345')
(4000,)
(14000, '11111')
Money Transfered Succesfully

           1. OPEN NEW ACCOUNT
           2. DEPOSIT AMOUNT
           3. WITHDRAW AMOUNT
           4. BALANCE ENQUIRY
           5. DISPLAY CUSTOMER DETAILS
           6. CLOSE AN ACCOUNT
           7. TRANSFER MONEY
Enter the Task You want to perform4
Enter the account no: 11111
Balanne for account:  11111 is 14000

           1. OPEN NEW ACCOUNT
           2. DEPOSIT AMOUNT
           3. WITHDRAW AMOUNT
           4. BALANCE ENQUIRY
           5. DISPLAY CUSTOMER DETAILS
           6. CLOSE AN ACCOUNT
           7. TRANSFER MONEY
Enter the Task You want to perform1
Enter The Name: Sinha
Enter the Accont No: 69699
Enter the date of Birth: 19/4/6
Enter The address: jharkhand(bihar)
Enter the contact number: 6969696
Enter the opening Balance: 100000
Data Entered Succesfully

           1. OPEN NEW ACCOUNT
           2. DEPOSIT AMOUNT
           3. WITHDRAW AMOUNT
           4. BALANCE ENQUIRY
           5. DISPLAY CUSTOMER DETAILS
           6. CLOSE AN ACCOUNT
           7. TRANSFER MONEY
Enter the Task You want to perform4
Enter the account no: 69699
Balanne for account:  69699 is 100000

           1. OPEN NEW ACCOUNT
           2. DEPOSIT AMOUNT
           3. WITHDRAW AMOUNT
           4. BALANCE ENQUIRY
           5. DISPLAY CUSTOMER DETAILS
           6. CLOSE AN ACCOUNT
           7. TRANSFER MONEY

In [ ]:

+-